[project]
name = "socrative-image-test-uploader"
version = "0.1.0"
description = "Tool for creating Socrative quizzes based on the CHOPS method."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "selenium>=4.35.0",
]
